services:
  nestjs_api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - NODE_ENV=development
    volumes:
      - ./src:/user/src/app/src
