services:
  mysql_db:
    image: mysql 
    ports:
      - '3307:3307'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nestjs_docker_mysql
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307
      
  nestjs_api_prod:
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - '8083:8083'
    environment:
      - PORT=8083
      - NODE_ENV=production
    volumes:
      - ./src:/user/src/app/src
